research_task:
  description: >
    Search the web for doctor conferences during 3 {months}  and for a given doctor {specialty}
    using the web scraper tool and serper tool. If the month is march then look for conferences happening in march, april and may.
    If the given months are November,December, January then look for conferences happening in November, December in the given year and January of the following year.
    If websites are not directly opened or too long  or needs downloads or any other blocks, move on.
  expected_output: >
    A list of maximum of 10 conferences happening during the given {months} for the given doctor {specialty} with
    names, dates,location and links.
  agent: researcher
  inputs: ["months", "specialty"]


report_task:
  description: >
    Review the context you got. Make sure report is detailed and contains all the relevant information.
  expected_output: >
    A list of conferences happening during the given {months} for the given doctor {specialty} with
    names, dates,location and links.
  agent: reporter
  output_file: output_research.md

email_task:
  description: 
    Structure an email listing the conferences to all the recipients in {email_list}.
    Ensure the email is well-structured, concise, and engaging starting with Hello , with salutation and regards with Lipi as name at the end with regards.
    Keep it structured, include names, dates,location and links. Avoid extra characters. Keep it professional.

  expected_output: >
    A fully drafted email with:
    - Subject: List of Upcoming {Specialty} Conferences in {months}
    - Body : Hello , List of conferences obtained
    Send the drafted email to the provided list of email addresses {email_list} by using the tool in structured points.
  agent: email_sender
  inputs: ["email_list","specialty"]